### ISSUE TITLE
Disable CORS except for specific URLs

### ISSUE THREAD

**Issue by LeaVerou** [madatajs/auth-serverless#5]
Currently CORS is enabled everywhere:

```toml
[headers.values]
    Access-Control-Allow-Origin = "*" 
```

This domain should not support CORS anywhere except specific URLs like `/services`. It's a security flaw if it does.
